CREATE TABLE energy_yearly_data (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key ,
                                    year INTEGER NOT NULL,
                                    january DOUBLE PRECISION NOT NULL,
                                    february DOUBLE PRECISION NOT NULL,
                                    march DOUBLE PRECISION NOT NULL,
                                    april DOUBLE PRECISION NOT NULL,
                                    may DOUBLE PRECISION NOT NULL,
                                    june DOUBLE PRECISION NOT NULL,
                                    july DOUBLE PRECISION NOT NULL,
                                    august DOUBLE PRECISION NOT NULL,
                                    september DOUBLE PRECISION NOT NULL,
                                    october DOUBLE PRECISION NOT NULL,
                                    november DOUBLE PRECISION NOT NULL,
                                    december DOUBLE PRECISION NOT NULL,
                                    client_id BIGINT NOT NULL,
                                    inverter_manufacturer_id BIGINT NOT NULL,
                                    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES client(id),
                                    CONSTRAINT fk_inverter FOREIGN KEY (inverter_manufacturer_id) REFERENCES inverter_manufacturer(id)
);
INSERT INTO inverter_manufacturer(id, name, portal_url) VALUES (1, 'GROWATT', 'https://server.growatt.com/?lang=pt');
INSERT INTO inverter_manufacturer(id, name, portal_url) VALUES (2, 'SOLIS', 'https://soliscloud.com/#/homepage');
INSERT INTO inverter_manufacturer(id, name, portal_url) VALUES (3, 'SUNGROW', 'https://isolarcloud.com/#/login');

INSERT INTO client(name, username, password, inverter_manufacturer_id) VALUES ('Lucimar Alves de Brito Dias', 'lucimarbrito', 'solar123', 1);
INSERT INTO client(name, username, password, inverter_manufacturer_id) VALUES ('Rodrigo Assano/Francisca Elisabetes', 'anderson.alexandre@gmail.com', 'sol@r123', 2);
INSERT INTO client(name, username, password, inverter_manufacturer_id) VALUES ('Jackson Gomes de Oliveira', 'jakson117@live.com', 'Sol@r!23', 3);
--INSERT INTO client(name, username, password, inverter_manufacturer_id) VALUES ('Ethan Comércio Atacadista de Confecções Eireli', 'ethancomercio', 'solar123', 1);